version: '3.8'

services:
  aktis-collector-jira:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD: ${BUILD:-unknown}
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    container_name: aktis-collector-jira
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./config:/app/config:ro
      - collector-data:/app/data
      - collector-logs:/app/logs
      - collector-backups:/app/backups
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_OUTPUT=${LOG_OUTPUT:-both}
      - SERVER_PORT=${PORT:-8080}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - aktis-network

volumes:
  collector-data:
    driver: local
  collector-logs:
    driver: local
  collector-backups:
    driver: local

networks:
  aktis-network:
    driver: bridge
